name: test

on: [workflow_dispatch]

jobs:
  clone-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3
      
    - name: Clone target repository
      run: git clone https://github.com/yano255/testtemp.git
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
        
    - name: Build and run Go application
      run: |
        cd testtemp
        go run main.go